name: Expo CI
on: 
  pull_request:
    branches:
      [ main ]
jobs:
  ci:
    name: Continuous Integration
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        node-version: [10.x, 12.x, 14.x]
        expo-version: [4.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use Expo ${{ matrix.expo-version }}
        uses: expo/expo-github-action@v6
        with:
          expo-version: ${{ matrix.expo-version }}
      - name: npm install, and expo doctor
        run: |
          npm install
          expo doctor
